version: "3"

services:
  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prom.yml:/etc/prometheus/prometheus.yml:Z
    ports:
    - 9090:9090

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    restart: always
    ports:
      - "3000:3000"

  libvirt_exporter:
    image: localhost/libvirt_exporter
    restart: always
    depends_on:
      - prometheus
    ports:
      - 5900:5900
    volumes:
      - /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock
