{
 "title": "Libvirt Exporter",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Node",
    "query": "label_values(libvirt_up, instance)"
   },
   {
    "name": "domain",
    "label": "Domain",
    "query": "label_values(libvirt_domain_state{instance=\"${instance}\"}, domain)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(libvirt_domain_info_cpu_time_seconds_total{instance=\"${instance}\"}[1m])",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "libvirt_domain_info_memory_rss_bytes{instance=\"${instance}\"}",
     "legendFormat": "{{domain}}_rss"
    },
    {
     "expr": "libvirt_domain_info_maximum_memory_bytes{instance=\"${instance}\", domain=\"${domain}\"}",
     "legendFormat": "{{domain}}_total"
    }
   ]
  },
  {
   "title": "Read / Write requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(libvirt_domain_block_read_requests_total{instance=\"${instance}\"}[1m])",
     "legendFormat": "{{domain}}_{{taget_device}}_read"
    },
    {
     "expr": "rate(libvirt_domain_block_write_requests_total{instance=\"${instance}\", domain=~\"${domain}\"}[1m])",
     "legendFormat": "{{domain}}_{{taget_device}}_write"
    }
   ]
  },
  {
   "title": "Read / Write Bytes per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(libvirt_domain_block_read_bytes_total{instance=\"${instance}\", domain=~\"${domain}\"}[1m])",
     "legendFormat": "{{domain}}_{{target_device}}_read"
    },
    {
     "expr": "rate(libvirt_domain_block_write_bytes_total{instance=\"${instance}\", domain=~\"${domain}\"}[1m])",
     "legendFormat": "{{domain}}_{{target_device}}_write"
    }
   ]
  },
  {
   "title": "Domain Status",
   "type": "graph",
   "description": "1 for running",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "libvirt_domain_state{instance=\"${instance}\", domain=~\"${domain}\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(libvirt_domain_interface_transmit_bytes_total{instance=\"${instance}\", domain=~\"${domain}\"}[1m])",
     "legendFormat": "{{domain}}_{{target_device}}_transmit"
    },
    {
     "expr": "rate(libvirt_domain_interface_receive_bytes_total{instance=\"${instance}\", domain=~\"${domain}\"}[1m])",
     "legendFormat": "{{domain}}_{{target_device}}_receive"
    }
   ]
  }
 ]
}